[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.93"
license = "Apache-2.0"
repository = "https://github.com/ston-fi/stonfi-sync-engine"
publish = false

[workspace.dependencies]
stonfi_metrics = { version = "0.0.1", git = "https://github.com/ston-fi/stonfi-metrics", rev = "v0.0.1" }
